name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull ${{ vars.DOCKER_USERNAME }}/node-app:latest
    - name: Delete Old docker container
      run: sudo docker rm -f ${{ vars.DOCKER_USERNAME }}/node-app:latest || true
    - name: Run Docker Container
      run: |
        docker stop node-app || true
        docker rm node-app || true
            
        # Pull the latest image
        docker pull ${{ vars.DOCKER_USERNAME }}/node-app:latest
            
        # Run the container
        docker run -d -p 5000:5000 \
            --name node-app \
            --env-file /home/ubuntu/.env \
            ${{ vars.DOCKER_USERNAME }}/node-app:latest
    - name: Run Docker Container
      run: echo "Deployment successful!"