name: CD_Pipeline

on:
  workflow_run:
    workflows: ["CI_Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete Old docker container
      run: sudo docker rm -f ${{ vars.DOCKER_USERNAME }}/node-app:latest || true
    - name: Run Docker Container
      run: |
        docker stop nodejs-app || true
        docker rm nodejs-app || true
        # Docker login
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
        
        # Pull the latest image
        docker pull ${{ vars.DOCKER_USERNAME }}/nodejs-app:latest
            
        # Run the container
        docker run -d -p 5000:5000 \
            --name node-app \
            --env-file /home/ubuntu/.env \
            ${{ vars.DOCKER_USERNAME }}/nodejs-app:latest
    - name: Run Docker Container
      run: echo "Deployment successful!"