name: CI Pipeline

on:
  push:
    branches: 
        - "master"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18    

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: echo "Skipping tests as none are defined"

  build:
    needs:  test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/nodejs-app:latest .
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/nodejs-app:latest .

      - name: Push to Docker Hub
        run: docker push ${{ vars.DOCKER_USERNAME }}/nodejs-app:latest
